import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToasterWithMax } from "./_wrappers/TosterWithMax";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <ToasterWithMax
          position="top-right"
          max={3}
          toastOptions={{ duration: 5000 }}
        />
        {children}
      </body>
    </html>
  );
}
