import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ToasterWithMax } from "../_wrappers/TosterWithMax";
import DashboardNavbar from "./_components/DashboardNavbar";
import { SidebarProvider, SidebarTrigger } from "../_components/ui/sidebar";
import { AppSidebar } from "./_components/AppSidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="h-full w-full">
        <DashboardNavbar />
        <ToasterWithMax
          position="top-right"
          max={3}
          toastOptions={{ duration: 5000 }}
        />

        {children}
      </main>
    </SidebarProvider>
  );
}
